apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "payment-platform.fullname" . }}
  labels:
    {{- include "payment-platform.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "payment-platform.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "payment-platform.name" . }}

    spec:
      containers:
        - name: payment-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 8080

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "payment-platform.fullname" . }}-config
                  key: APP_ENV

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/paymentdb"

            - name: SPRING_DATASOURCE_USERNAME
              value: "paymentuser"

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "payment-platform.fullname" . }}-secret
                  key: db-password

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
