
{{- if .Values.serviceMonitor.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: payment-monitor

spec:
  selector:
    matchLabels:
      app: payment-platform

  endpoints:
    - port: http
      interval: 15s

{{- end }}
